name: Build Email Templates
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Clean Install dependencies and Build
        run: |
          npm install
          gulp
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: build
          FOLDER: 'build'

      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build
