name: Build email templates
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: "14"
    - run: npm install
    - run: gulp

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: build
        FOLDER: "build"

    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: build
        path: build
